version: '3'

services:
  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: personal
      POSTGRES_PASSWORD: pass123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # app:
  #   build: .
  #   environment:
  #     DATABASE_URL: postgresql://postgres:pass123@postgres:5432/personal?schema=public
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8080:8080"

volumes:
  postgres_data: